# Generated by Django 4.0.5 on 2022-07-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_cz_record_cze_rename_en_record_eng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='translator',
        ),
        migrations.AddField(
            model_name='record',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Author's name of translation"),
        ),
    ]
