# Generated by Django 4.0.5 on 2022-07-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_record_translator_record_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='special_cze',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Special notes'),
        ),
        migrations.AlterField(
            model_name='record',
            name='special_eng',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Special notes'),
        ),
    ]
