# Generated by Django 4.0.5 on 2022-07-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_record_cze_alter_record_eng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='cze',
            field=models.CharField(max_length=200, verbose_name='Word in CZech'),
        ),
        migrations.AlterField(
            model_name='record',
            name='eng',
            field=models.CharField(max_length=200, verbose_name='Word in ENglish'),
        ),
    ]
