# Generated by Django 4.0.5 on 2022-07-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_record_notes_cze_alter_record_notes_eng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='cze',
            field=models.CharField(max_length=300, verbose_name='Word in CZech'),
        ),
        migrations.AlterField(
            model_name='record',
            name='eng',
            field=models.CharField(max_length=300, verbose_name='Word in ENglish'),
        ),
    ]
